Cathy NANGINI<br>
Dataviz Scientist at LSCE (Climate and Environment Sciences Laboratory)<br>
<img align="left" width="40%" src="http://www.lsce.ipsl.fr/Css/img/banniere_LSCE_75.png"><br><br>
<hr>

Coded: 15.02.2016
Last modified: 18.02.2016

In [1]:
import numpy as np
import pandas as pd
import collections
import os

In [2]:
num_analogues = 20 #number of analogues searched for

In [3]:
# Create dataframe from analogues file

dfS = pd.DataFrame()
dfS = pd.read_csv('analogues.tsv', delimiter=' ', index_col=0)
#dfS.set_index('Date', inplace=True)

dfS.tail(10)

#dfS.index.name

,date.an1,date.an2,date.an3,date.an4,date.an5,date.an6,date.an7,date.an8,date.an9,date.an10,...,cor11,cor12,cor13,cor14,cor15,cor16,cor17,cor18,cor19,cor20
date,,,,,,,,,,,,,,,,,,,,,
20151216,19481130,19481129,19831124,19481210,19721216,19771221,19481201,19711218,19941201,19721215,...,0.858417,0.600339,0.580164,0.667006,0.649544,0.706988,0.679815,0.613030,0.492617,0.566106
20151217,19831124,19741224,20001211,19971223,19911123,20001202,20061129,19481205,20091120,20001203,...,0.649169,0.625368,0.566788,0.691608,0.612326,0.447951,0.652282,0.725638,0.604856,0.457750
20151218,20091120,19741221,19741225,19741222,20061126,19761127,19911123,20091121,19911124,19981228,...,0.623932,0.685005,0.665350,0.556471,0.728755,0.601237,0.570927,0.565296,0.545892,0.773745
20151219,20091121,20070107,20000105,20061202,19741225,19911125,20131230,20050111,19681125,19620109,...,0.634742,0.718378,0.658484,0.674121,0.698979,0.833905,0.548934,0.684943,0.484342,0.761014
20151220,20070107,19901231,19900119,20070117,20061202,19721204,19990117,20061203,19891222,19761130,...,0.739972,0.742671,0.741633,0.609813,0.759362,0.825590,0.744857,0.658490,0.740220,0.680282
20151221,19930120,19930119,20050110,20061231,20050109,20061202,20050108,20131222,20070117,20131223,...,0.749093,0.810943,0.756179,0.791931,0.744660,0.784398,0.739902,0.738095,0.759026,0.818859
20151222,20131222,20050110,20131221,20150112,19890111,19930120,20131223,20050109,20150113,20050108,...,0.831017,0.805147,0.774792,0.737730,0.770455,0.805592,0.788998,0.795123,0.793576,0.837264
20151223,20050110,20131222,20150113,20050109,19481203,20070115,19930120,20050108,20150112,20050107,...,0.723753,0.813239,0.793027,0.822214,0.700882,0.756600,0.758402,0.737111,0.757936,0.776397
20151224,19750112,20050110,19861203,19990119,19481203,20050111,19830111,19741222,20001212,20070115,...,0.753615,0.756670,0.614877,0.640223,0.661410,0.659859,0.523267,0.694998,0.522598,0.645233
20151225,20080120,19990105,20061215,19970118,19771224,19571222,20111201,19921217,19531127,19760108,...,0.654542,0.650501,0.595649,0.632474,0.661503,0.522062,0.603675,0.479803,0.559736,0.655751

In [10]:
dfS_cut = dfS[dfS.index > 20000101]
dfS_cut
#df[(df.A == 1)]

,date.an1,date.an2,date.an3,date.an4,date.an5,date.an6,date.an7,date.an8,date.an9,date.an10,...,cor11,cor12,cor13,cor14,cor15,cor16,cor17,cor18,cor19,cor20
date,,,,,,,,,,,,,,,,,,,,,
20000102,20060110,19631229,20110116,19821225,19780106,19830101,19680119,20080124,20111222,19900115,...,0.654698,0.655488,0.802203,0.666135,0.643223,0.668773,0.671843,0.541877,0.679896,0.503864
20000103,20110116,20060110,19740124,20080124,19900115,19931204,19631229,19721210,19900116,19830101,...,0.597911,0.674042,0.707166,0.675105,0.672872,0.661090,0.672815,0.635037,0.628584,0.757617
20000104,20061213,19740124,19801213,19900116,19990118,19620120,19801223,19801224,19721210,19760107,...,0.751647,0.700169,0.728417,0.727735,0.781636,0.648881,0.744938,0.692383,0.671573,0.627335
20000105,20070107,19981217,20050111,19990120,19740123,19620109,19801213,19801214,19610129,19990119,...,0.604475,0.635757,0.698113,0.577584,0.772600,0.533498,0.472937,0.776194,0.542668,0.666600
20000106,20060111,19981224,19721210,19981225,19890112,19740124,19570127,19900115,19740125,19910101,...,0.682861,0.642880,0.750071,0.738293,0.672061,0.658758,0.739775,0.744389,0.614146,0.777380
20000107,20131221,19750122,19901229,19830106,19981226,19901230,19561212,20061211,19830105,19511224,...,0.673018,0.744757,0.784891,0.677292,0.835722,0.756660,0.670062,0.829350,0.770471,0.761213
20000108,19890204,19830107,19940122,19481229,20041216,19731227,19650114,19911218,19640130,20061211,...,0.687549,0.765553,0.708579,0.580866,0.713276,0.711383,0.770307,0.646411,0.664310,0.698271
20000109,19731227,20041215,19830108,20041231,19731228,20110131,19731226,19870204,19890202,19890207,...,0.752161,0.650239,0.757048,0.844279,0.769735,0.665189,0.757044,0.743272,0.747552,0.645753
20000110,19511221,19900109,19520107,19511222,19631229,19571226,19771214,19560104,20071224,19780106,...,0.758365,0.755010,0.636018,0.791232,0.661322,0.594798,0.761684,0.486696,0.646400,0.713742
20000111,20071224,19670205,19490106,19571227,19890120,19731229,19721222,19810108,19810123,19830111,...,0.674300,0.636636,0.809313,0.694933,0.630220,0.756036,0.622366,0.634700,0.696370,0.592672
20000112,19901219,19810129,19770106,19670206,19490107,19680121,19531227,19701219,19731230,19830112,...,0.536588,0.529336,0.573163,0.553263,0.572562,0.696292,0.499187,0.614696,0.435652,0.620736
20000113,19681230,19830210,20090105,20090104,20110124,19901219,19810129,19970102,19980126,19490108,...,0.428912,0.575181,0.569819,0.357860,0.428883,0.416889,0.515153,0.424181,0.556337,0.491005
20000114,20110123,20120213,20110124,19970102,19711227,20061218,19680121,19980126,19901219,19970101,...,0.519006,0.537207,0.552581,0.413758,0.508386,0.588280,0.535525,0.581275,0.506201,0.519557
20000115,19920127,19590129,19921227,19570115,19791220,19970127,19570116,19930207,19680121,20010115,...,0.577967,0.584099,0.633709,0.511892,0.608207,0.696593,0.420714,0.573624,0.593476,0.511781
20000116,19710204,19680122,19770107,19930208,19970128,20150207,19650210,19970127,19680123,19810111,...,0.491265,0.665865,0.683444,0.535994,0.679417,0.660423,0.483548,0.717691,0.590444,0.624135
20000117,19830119,19640124,19770108,19650210,19600210,20011222,20050131,20050122,20110101,20110102,...,0.718865,0.617496,0.697336,0.674181,0.728170,0.793885,0.579328,0.716854,0.711746,0.615737
20000118,19830119,20050122,19861221,19810105,19761225,19611221,20110102,19580217,19701231,19761226,...,0.664232,0.757612,0.649065,0.665272,0.708254,0.685454,0.700795,0.735244,0.732998,0.566949
20000119,19830119,19810105,19600116,20090104,19810106,20090105,20050122,19761225,20011220,19540109,...,0.630647,0.565640,0.700973,0.678283,0.565550,0.552646,0.577346,0.554187,0.578562,0.582579
20000120,19911224,20150207,19920116,19830119,19670208,19570111,20070122,20050219,19760124,19810106,...,0.741475,0.558822,0.683851,0.693089,0.629020,0.706703,0.754194,0.543962,0.633631,0.634927
20000121,19830119,19810105,19911224,19570111,19770108,19600116,19580219,19580218,19810106,19920116,...,0.623227,0.679200,0.586521,0.627809,0.588682,0.585468,0.669144,0.661542,0.665812,0.601861
20000122,19810105,19760124,20070122,20110124,20050219,20090104,20050218,20070121,19810106,20070123,...,0.740135,0.688115,0.718625,0.693010,0.719121,0.711290,0.624711,0.634374,0.561337,0.666308
20000123,20050219,20070123,20110125,19760125,20130207,19530106,20110124,19670208,19940116,19570113,...,0.695115,0.565939,0.691732,0.603057,0.622727,0.663783,0.561185,0.540051,0.641469,0.647110
20000124,20150205,19930222,19570113,19830212,20110126,19590129,19530106,19530204,19700216,19630113,...,0.601646,0.628033,0.539244,0.672827,0.560449,0.637211,0.616529,0.611901,0.704877,0.681027
20000125,19540204,19680122,19980125,19540105,19680124,19570117,20150206,19780115,20070203,20080129,...,0.657749,0.548022,0.527575,0.596639,0.508937,0.623063,0.519479,0.604872,0.650589,0.435932
20000126,19680122,19540106,20070203,19930217,20080129,19810209,19530120,19670206,19930218,20010215,...,0.676689,0.593216,0.691486,0.613284,0.619075,0.487933,0.622812,0.679173,0.595431,0.664344
20000127,19490224,19780102,19490225,19751228,19930217,20020217,19930218,20010215,20120224,19571228,...,0.667355,0.663584,0.689881,0.739414,0.671282,0.584789,0.677275,0.676736,0.534515,0.504156
20000128,20070113,19790109,19730206,20050111,19950222,20070114,20070111,19751229,20070115,19620120,...,0.671267,0.668958,0.623192,0.673908,0.630684,0.712688,0.620038,0.677631,0.695552,0.656276
20000129,19950217,19840115,19610130,20050108,20150113,19750123,19840103,20070111,19860123,19970225,...,0.611683,0.793964,0.792682,0.683142,0.676002,0.700979,0.777426,0.644306,0.690497,0.710926
20000130,19970226,19930122,19900208,19970212,20030116,20050108,20070104,20080222,19640131,20070102,...,0.614999,0.573383,0.651207,0.635095,0.799564,0.793067,0.708978,0.573311,0.636726,0.777241
20000131,20030116,19970226,19900209,19930122,19890207,19530221,19930114,19920104,20070116,19970212,...,0.776461,0.671816,0.715354,0.698774,0.799195,0.653821,0.735173,0.784027,0.727419,0.806640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20151126,19821115,20141206,19741208,19831101,19801223,19711125,19741213,20141203,19821224,19821225,...,0.740972,0.716895,0.674204,0.720729,0.675780,0.721909,0.641328,0.703864,0.718062,0.605876
20151127,19571031,19831101,19821115,19571101,19801224,19801223,20111203,20031028,19731112,20111206,...,0.624066,0.733649,0.692916,0.710360,0.718487,0.661530,0.698455,0.664268,0.651222,0.596139
20151128,19911219,19571031,19491203,20141218,19821117,19601203,20111203,20041216,19911218,19571101,...,0.793886,0.709969,0.704914,0.689036,0.738930,0.766606,0.690386,0.694186,0.603395,0.649960
20151129,19911218,20141218,19911219,19491203,20141219,20111203,19901117,20061212,19551228,19741228,...,0.697498,0.680616,0.668068,0.642518,0.488885,0.567634,0.645796,0.698986,0.668722,0.631966
20151130,20101103,19781116,19901117,20091123,19641124,19741226,20141220,20141222,19881222,19631120,...,0.635707,0.645316,0.693999,0.677112,0.721446,0.654085,0.658450,0.621866,0.705381,0.573239
20151201,19801212,19801213,19771110,19821228,19861206,19941118,19991205,19941117,19941121,19981216,...,0.785240,0.667464,0.514155,0.631030,0.599253,0.700436,0.581541,0.558405,0.715658,0.598201
20151202,19921127,20150101,19561210,19901231,19721210,19761125,19481116,19561211,19731108,19991103,...,0.617280,0.659062,0.602603,0.707194,0.629690,0.594049,0.632712,0.630008,0.569169,0.515413
20151203,19511219,19631229,19721210,19830102,19511223,19781110,19761126,19481116,20131216,19781108,...,0.749354,0.617781,0.642156,0.623447,0.697348,0.632852,0.668751,0.518966,0.545728,0.595425
20151204,19721211,19721210,20131217,19481116,19830103,20061231,19561211,19561210,19781113,20131216,...,0.697919,0.639852,0.756320,0.779316,0.753412,0.675676,0.702289,0.727866,0.809023,0.703702
20151205,20131222,20061212,20061231,19821110,19721213,19920102,20131221,20061211,19911218,19561214,...,0.645922,0.797736,0.770956,0.629852,0.772115,0.759727,0.561200,0.733119,0.700557,0.713399
20151206,19531201,19531130,19920103,19920104,20111126,19781118,20111127,19771109,19781116,19781119,...,0.767223,0.755595,0.740683,0.623042,0.645220,0.726330,0.674669,0.605643,0.624703,0.696780
20151207,19821207,19861112,19861204,19861202,19861203,19531205,19771110,19481204,19781117,19531114,...,0.593132,0.673304,0.596947,0.535221,0.532721,0.385865,0.742323,0.569778,0.571827,0.349791
20151208,19531115,19890103,19481205,19481116,20051109,19841206,19631229,19941203,19941205,19781111,...,0.625002,0.632086,0.517581,0.501394,0.583489,0.447500,0.550635,0.680111,0.453791,0.412115
20151209,20051110,20111124,19631229,19781114,20051109,19481117,19861127,19481118,19711215,20071228,...,0.701566,0.572599,0.603248,0.603329,0.636799,0.572885,0.498126,0.543046,0.496353,0.585287
20151210,20081114,19571227,19781114,19831204,19731229,19521210,19780109,19531111,19911213,20051110,...,0.612156,0.694980,0.703954,0.609458,0.533252,0.561988,0.601345,0.631100,0.688481,0.644641
20151211,20081115,20081114,19521211,19531112,19711216,19851213,19911213,19941211,19831204,19571227,...,0.670288,0.607615,0.533139,0.622991,0.496535,0.550534,0.605327,0.461172,0.543164,0.417636
20151212,19941212,19531113,20081115,19811123,19811122,19531112,19711216,19751115,19801123,19731119,...,0.516390,0.505001,0.596398,0.378924,0.496120,0.284742,0.138413,0.531514,0.406716,0.557781
20151213,19741120,19731120,19731118,19531113,19531114,20010109,19731119,19481209,19711217,19851208,...,0.449674,0.628532,0.541038,0.360536,0.576355,0.575193,0.449258,0.493825,0.399651,0.341313
20151214,19741120,20021219,19481129,19481209,19851129,19531114,19741121,19551114,19710105,19481210,...,0.542417,0.641696,0.459903,0.588127,0.550295,0.628490,0.599936,0.496451,0.627527,0.524928
20151215,19481129,19710105,19481130,19741121,19721216,19970110,19970111,19481210,19741120,19771221,...,0.690619,0.626364,0.649650,0.639726,0.642178,0.526290,0.562140,0.502471,0.616818,0.709604
20151216,19481130,19481129,19831124,19481210,19721216,19771221,19481201,19711218,19941201,19721215,...,0.858417,0.600339,0.580164,0.667006,0.649544,0.706988,0.679815,0.613030,0.492617,0.566106
20151217,19831124,19741224,20001211,19971223,19911123,20001202,20061129,19481205,20091120,20001203,...,0.649169,0.625368,0.566788,0.691608,0.612326,0.447951,0.652282,0.725638,0.604856,0.457750
20151218,20091120,19741221,19741225,19741222,20061126,19761127,19911123,20091121,19911124,19981228,...,0.623932,0.685005,0.665350,0.556471,0.728755,0.601237,0.570927,0.565296,0.545892,0.773745
20151219,20091121,20070107,20000105,20061202,19741225,19911125,20131230,20050111,19681125,19620109,...,0.634742,0.718378,0.658484,0.674121,0.698979,0.833905,0.548934,0.684943,0.484342,0.761014
20151220,20070107,19901231,19900119,20070117,20061202,19721204,19990117,20061203,19891222,19761130,...,0.739972,0.742671,0.741633,0.609813,0.759362,0.825590,0.744857,0.658490,0.740220,0.680282
20151221,19930120,19930119,20050110,20061231,20050109,20061202,20050108,20131222,20070117,20131223,...,0.749093,0.810943,0.756179,0.791931,0.744660,0.784398,0.739902,0.738095,0.759026,0.818859
20151222,20131222,20050110,20131221,20150112,19890111,19930120,20131223,20050109,20150113,20050108,...,0.831017,0.805147,0.774792,0.737730,0.770455,0.805592,0.788998,0.795123,0.793576,0.837264
20151223,20050110,20131222,20150113,20050109,19481203,20070115,19930120,20050108,20150112,20050107,...,0.723753,0.813239,0.793027,0.822214,0.700882,0.756600,0.758402,0.737111,0.757936,0.776397
20151224,19750112,20050110,19861203,19990119,19481203,20050111,19830111,19741222,20001212,20070115,...,0.753615,0.756670,0.614877,0.640223,0.661410,0.659859,0.523267,0.694998,0.522598,0.645233
20151225,20080120,19990105,20061215,19970118,19771224,19571222,20111201,19921217,19531127,19760108,...,0.654542,0.650501,0.595649,0.632474,0.661503,0.522062,0.603675,0.479803,0.559736,0.655751

In [16]:
#SAVE DATE INDEX
#DF['id2'] = DF.index
dfS['dateRef'] = dfS.index
dfS['dateRef'].head(10)

date
19480101    19480101
19480102    19480102
19480103    19480103
19480104    19480104
19480105    19480105
19480106    19480106
19480107    19480107
19480108    19480108
19480109    19480109
19480110    19480110
Name: dateRef, dtype: int64

In [11]:
dfS_cut['dateRef'] = dfS_cut.index
dfS_cut['dateRef'].head(10)

/usr/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

date
20000102    20000102
20000103    20000103
20000104    20000104
20000105    20000105
20000106    20000106
20000107    20000107
20000108    20000108
20000109    20000109
20000110    20000110
20000111    20000111
Name: dateRef, dtype: int64

In [17]:
#CREATE ANALOGUE DATE TABLE ONLY
#s1.iloc[:3] #selects rows only
# df1.iloc[1:5,2:4] #selects rows, cols
dfA_raw = dfS.iloc[:, 0:20]
dfA_raw.head(10)

,date.an1,date.an2,date.an3,date.an4,date.an5,date.an6,date.an7,date.an8,date.an9,date.an10,date.an11,date.an12,date.an13,date.an14,date.an15,date.an16,date.an17,date.an18,date.an19,date.an20
date,,,,,,,,,,,,,,,,,,,,
19480101,19560126,19850131,20110114,19551224,19850130,19980114,19521221,20001211,19681220,19871224,19870101,19540119,19610109,19560125,20010108,20110112,19651223,19651213,20110113,20031209
19480102,20001211,19681221,19551224,20110112,19560126,19741220,19600121,19681220,19521221,19850131,19741219,19670126,19600119,20001212,19971223,19681222,19741221,20110114,19980108,19851223
19480103,19491206,19741222,19750110,19851222,19641231,19921215,19741221,19931217,19950124,19491207,19991211,19750109,20031217,19921216,19991212,19741225,20020120,19921214,19600120,19681220
19480104,20031217,19891221,19921215,19510114,20020121,19931218,19921216,19741224,19931217,19851222,19550120,19641231,19741223,19491206,19491207,19971209,19681220,19921206,19871218,19551224
19480105,19971210,19971209,19971211,19591230,19931217,19591228,19591229,19950129,20020121,19550120,19931218,19861228,19741224,20020122,19510114,19551224,19680115,19861230,20010104,20020120
19480106,20020122,19710120,19931217,19591227,19991211,20020121,19991210,19950129,19710126,19781214,20040113,19510112,19591228,20020120,20031227,19811213,19891221,19610131,20030102,19861230
19480107,19781214,19591227,19510112,19811214,19991211,19591228,19581213,19571210,20040114,19811213,19830131,19950128,19651210,19991212,20030102,19660102,19991210,19891218,20040113,19991209
19480108,20040114,19591228,19781214,19931217,19811213,19510113,19660102,20030102,19740205,19811214,19991211,19681220,19550119,19991210,19950128,19510112,20020122,19660206,19850126,19950129
19480109,20021230,20020121,19931217,19681220,19861230,19590114,19660206,19811213,19660207,20021229,19590113,20010104,19551221,19850126,19850127,19850125,19550206,19580207,19740208,20110114
19480110,19550128,19710116,19800130,19850126,20030101,20020122,20020121,19590114,19851230,19861231,19550129,20021230,20020125,19831224,19580207,19850125,19950130,19950127,19861230,20030102

In [12]:
dfA_cut_raw = dfS_cut.iloc[:, 0:20]
dfA_cut_raw.head(10)

,date.an1,date.an2,date.an3,date.an4,date.an5,date.an6,date.an7,date.an8,date.an9,date.an10,date.an11,date.an12,date.an13,date.an14,date.an15,date.an16,date.an17,date.an18,date.an19,date.an20
date,,,,,,,,,,,,,,,,,,,,
20000102,20060110,19631229,20110116,19821225,19780106,19830101,19680119,20080124,20111222,19900115,20120118,19760107,19821231,19520106,19830102,19931203,19720122,20110117,20060109,19721210
20000103,20110116,20060110,19740124,20080124,19900115,19931204,19631229,19721210,19900116,19830101,19760107,20111222,20111223,19511219,19801223,19740123,19821225,19561211,19780106,19571220
20000104,20061213,19740124,19801213,19900116,19990118,19620120,19801223,19801224,19721210,19760107,19910104,19840116,19750125,20060111,19900115,19981217,20070114,19711224,19480113,19650113
20000105,20070107,19981217,20050111,19990120,19740123,19620109,19801213,19801214,19610129,19990119,20031226,19620108,19740124,20020120,20070106,19971210,19510108,19901230,19971207,19901231
20000106,20060111,19981224,19721210,19981225,19890112,19740124,19570127,19900115,19740125,19910101,19930120,19900120,19981226,19930109,19511223,19990118,19760119,19910104,19721211,19511218
20000107,20131221,19750122,19901229,19830106,19981226,19901230,19561212,20061211,19830105,19511224,20131222,19650113,19981225,19561213,19571220,19910102,19561214,19570120,19901226,19481229
20000108,19890204,19830107,19940122,19481229,20041216,19731227,19650114,19911218,19640130,20061211,19620204,20050101,19640129,19930108,19830106,20050107,20041215,19520109,20050118,19890206
20000109,19731227,20041215,19830108,20041231,19731228,20110131,19731226,19870204,19890202,19890207,19930106,19750101,20150101,19890128,20060111,20111224,19890205,20020115,20110201,19511223
20000110,19511221,19900109,19520107,19511222,19631229,19571226,19771214,19560104,20071224,19780106,19941224,19620209,20071223,19721222,19481228,19740123,19930202,19821225,20120118,19890119
20000111,20071224,19670205,19490106,19571227,19890120,19731229,19721222,19810108,19810123,19830111,20120118,20120110,19770105,19830112,19921224,19950108,19990203,19780109,19511222,19771215

In [13]:
dfA_raw.shape

NameError: name 'dfA_raw' is not defined

In [14]:
dfA_cut_raw.shape

(5837, 20)

In [19]:
20*24831

496620

In [20]:
#STACK ANALOGUE DATES ACROSS COLUMNS INTO ONE COLUMN

#first remove index name of dfA_raw
dfA_raw.index.name = ""

dfA_stack = dfA_raw.stack()
dfA_stack.index.name

In [16]:
#CUT

#first remove index name of dfA_raw
dfA_cut_raw.index.name = ""

dfA_cut_stack = dfA_cut_raw.stack()
dfA_cut_stack.index.name

In [17]:
dfA_cut_stack

20000102  date.an1     20060110
          date.an2     19631229
          date.an3     20110116
          date.an4     19821225
          date.an5     19780106
          date.an6     19830101
          date.an7     19680119
          date.an8     20080124
          date.an9     20111222
          date.an10    19900115
          date.an11    20120118
          date.an12    19760107
          date.an13    19821231
          date.an14    19520106
          date.an15    19830102
          date.an16    19931203
          date.an17    19720122
          date.an18    20110117
          date.an19    20060109
          date.an20    19721210
20000103  date.an1     20110116
          date.an2     20060110
          date.an3     19740124
          date.an4     20080124
          date.an5     19900115
          date.an6     19931204
          date.an7     19631229
          date.an8     19721210
          date.an9     19900116
          date.an10    19830101
                         ...
20151224  date.an11    20111129
          date.an12    19981228
          date.an13    19991127
          date.an14    20061214
          date.an15    19481204
          date.an16    19531202
          date.an17    19731210
          date.an18    20020120
          date.an19    19731229
          date.an20    19741221
20151225  date.an1     20080120
          date.an2     19990105
          date.an3     20061215
          date.an4     19970118
          date.an5     19771224
          date.an6     19571222
          date.an7     20111201
          date.an8     19921217
          date.an9     19531127
          date.an10    19760108
          date.an11    19890116
          date.an12    20140108
          date.an13    19941211
          date.an14    20061216
          date.an15    20061214
          date.an16    19990120
          date.an17    20080119
          date.an18    19821125
          date.an19    19890117
          date.an20    19590123
dtype: int64

In [22]:
#list(dfA_stack)

In [23]:
#CREATE EMPTY DATAFRAME WITH NUM ROWS = NUM COLS OF dfA_raw
index = dfA_raw.shape[0] #num cols of dfA
columns = 2
dfA = pd.DataFrame(np.nan, index=range(0, dfA_raw.shape[0]), columns=['dateAnlg'])

#dfA = pd.DataFrame(np.nan, index=range(0,4), columns=['Adate'])

dfA.shape

(24831, 1)

In [19]:
#CUT
index_cut = dfA_cut_raw.shape[0] #num cols of dfA
columns = 2
dfA_cut = pd.DataFrame(np.nan, index=range(0, dfA_cut_raw.shape[0]), columns=['dateAnlg'])

#dfA = pd.DataFrame(np.nan, index=range(0,4), columns=['Adate'])

dfA_cut.shape

(5837, 1)

In [24]:
#REPLACE INDEX COL OF dfA WITH ORIG date_id
dfA = dfA.set_index(dfS['dateRef'])
dfA.head(10)
#dfA.shape

          dateAnlg
dateRef
19480101       NaN
19480102       NaN
19480103       NaN
19480104       NaN
19480105       NaN
19480106       NaN
19480107       NaN
19480108       NaN
19480109       NaN
19480110       NaN

In [21]:
dfA_cut = dfA_cut.set_index(dfS_cut['dateRef'])
dfA_cut.head(10)

          dateAnlg
dateRef
20000102       NaN
20000103       NaN
20000104       NaN
20000105       NaN
20000106       NaN
20000107       NaN
20000108       NaN
20000109       NaN
20000110       NaN
20000111       NaN

In [25]:
#REPLICATE INDEX COL 20 TIMES PER ROW

#http://stackoverflow.com/questions/26777832/replicating-rows-in-a-pandas-data-frame-by-a-column-value
#df2 = df.loc[np.repeat(df.index.values,df.n)]
dfA = dfA.loc[np.repeat(dfA.index.values,num_analogues)]

In [22]:
dfA_cut = dfA_cut.loc[np.repeat(dfA_cut.index.values,num_analogues)]

In [26]:
dfA.head(30)

          dateAnlg
dateRef
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480101       NaN
19480102       NaN
19480102       NaN
19480102       NaN
19480102       NaN
19480102       NaN
19480102       NaN
19480102       NaN
19480102       NaN
19480102       NaN
19480102       NaN

In [23]:
dfA_cut.head(30)

          dateAnlg
dateRef
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000102       NaN
20000103       NaN
20000103       NaN
20000103       NaN
20000103       NaN
20000103       NaN
20000103       NaN
20000103       NaN
20000103       NaN
20000103       NaN
20000103       NaN

In [27]:
#REPLACE COL 0 WITH STACKED DATES
dfA.iloc[:,0] = list(dfA_stack)

In [25]:
dfA_cut.iloc[:,0] = list(dfA_cut_stack)
dfA_cut.head(30)

          dateAnlg
dateRef
20000102  20060110
20000102  19631229
20000102  20110116
20000102  19821225
20000102  19780106
20000102  19830101
20000102  19680119
20000102  20080124
20000102  20111222
20000102  19900115
20000102  20120118
20000102  19760107
20000102  19821231
20000102  19520106
20000102  19830102
20000102  19931203
20000102  19720122
20000102  20110117
20000102  20060109
20000102  19721210
20000103  20110116
20000103  20060110
20000103  19740124
20000103  20080124
20000103  19900115
20000103  19931204
20000103  19631229
20000103  19721210
20000103  19900116
20000103  19830101

In [28]:
dfA.head(30)

          dateAnlg
dateRef
19480101  19560126
19480101  19850131
19480101  20110114
19480101  19551224
19480101  19850130
19480101  19980114
19480101  19521221
19480101  20001211
19480101  19681220
19480101  19871224
19480101  19870101
19480101  19540119
19480101  19610109
19480101  19560125
19480101  20010108
19480101  20110112
19480101  19651223
19480101  19651213
19480101  20110113
19480101  20031209
19480102  20001211
19480102  19681221
19480102  19551224
19480102  20110112
19480102  19560126
19480102  19741220
19480102  19600121
19480102  19681220
19480102  19521221
19480102  19850131

In [26]:
#SAVE TO TSV FILE

#dfA.to_csv('analogues_reformat.tsv', sep='\t')
dfA_cut.to_csv('analogues_reformat_cut.tsv', sep='\t')

In [27]:
dfA_cut.shape

(116740, 1)